# Generated by Django 6.1.1 on 2026-09-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaonda', '0002_suite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='suite',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
