# Generated by Django 6.1.1 on 2026-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaonda', '0003_foto_alter_suite_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='foto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suite',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='suites/'),
        ),
    ]
