# Generated by Django 6.1.1 on 2026-09-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaonda', '0004_foto_ativo_foto_descricao_foto_imagem_foto_ordem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeDaManha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cafe-da-manha/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
