# Generated by Django 6.1.1 on 2026-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaonda', '0006_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='servico',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para aparecer maior (ex: Spa)'),
        ),
        migrations.AddField(
            model_name='servico',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
    ]
