# Generated by Django 6.1.1 on 2026-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaonda', '0007_alter_servico_options_servico_destaque_servico_ordem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
